name: app_toolbox_rd
description: Una aplicación de múltiples utilidades.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  xml: ^6.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/adulto.png
    - lib/assets/images/anciano.png
    - lib/assets/images/joven.png
    - lib/assets/images/mi_foto.jpg
